ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

Previously we could only turn these on, but now the BLEManager exposes
methods to disable notifications and indication updates.

NRF Toolbox: support disabling notifications

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

Fix for NPE when device gets disconnected by turning off Bluetooth (#58).

Bugfix: #58

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

Bugfix: #61

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

This PR removes final modifier in most request methods in BleManager.
Referenced issue: #55.

Opening API (#55)

---

ble/src/main/java/no/nordicsemi/android/ble/ConnectRequest.java
ble/src/main/java/no/nordicsemi/android/ble/TimeoutableRequest.java
ble/src/main/java/no/nordicsemi/android/ble/TimeoutableValueRequest.java

TimeoutableRequest made public

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
gradle.properties

Version 2.2.0-alpha02

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java
ble/src/main/java/no/nordicsemi/android/ble/ConditionalWaitRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ReadRssiRequest.java
ble/src/main/java/no/nordicsemi/android/ble/SleepRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForValueChangedRequest.java
gradle.properties

Changes from version 2.2.0-alpah02:
- Restoring `Operation` interface for all requests.
- Fixed sending notifications on pre-Lollipop devices.
- Issues fixed.

Version 2.2.0-alpha03

---

ble/build.gradle
build.gradle
gradle.properties
gradle/gradle-bintray-push.gradle

Publication script updated. POM contains dependencies.

Version 2.2.0-alpha04

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java
ble/src/main/java/no/nordicsemi/android/ble/annotation/CharacteristicPermissions.java
ble/src/main/java/no/nordicsemi/android/ble/annotation/CharacteristicProperties.java
ble/src/main/java/no/nordicsemi/android/ble/annotation/DescriptorPermissions.java
gradle.properties

Improvements:
* Helper methods added to `BleServerManager`.

Version 2.2.0-alpha05

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/callback/DisconnectCallback.java

This allows registering callback for disconnect but with status report.

Add extended disconnect callback (closes #110)

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java
ble/src/main/java/no/nordicsemi/android/ble/CallbackHandler.java
ble/src/main/java/no/nordicsemi/android/ble/Request.java
ble/src/main/java/no/nordicsemi/android/ble/RequestHandler.java
ble/src/main/java/no/nordicsemi/android/ble/ValueChangedCallback.java
ble/src/main/java/no/nordicsemi/android/ble/annotation/DescriptorPermissions.java
ble/src/main/java/no/nordicsemi/android/ble/callback/DisconnectCallback.java
ble/src/main/java/no/nordicsemi/android/ble/data/Data.java
ble/src/test/java/no/nordicsemi/android/ble/RequestTest.java
build.gradle
gradle.properties
gradle/gradle-bintray-push.gradle
gradle/wrapper/gradle-wrapper.properties

New in this version:
* #110 fixed with #149 
* Option to call a method using callback handler
* #154 fixed
* #161 and #162 implemented
* Option to set handler for ValueChangedCallback

Versio 2.2.0-alpha07

---

README.md
gradle.properties
gradle/gradle-bintray-push.gradle

New in this version:
* Callbacks have been redesigned, see #174.

Version 2.2.0-alpha08

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java
ble/src/main/java/no/nordicsemi/android/ble/observer/ServerObserver.java
build.gradle
gradle.properties

Version 2.2.0-alpha10

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/Request.java
gradle.properties

Version 2.2.0-alpha12

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
gradle.properties

Bugs fixed: 
* #184 - this issue, in a bit different form, was there for a long time. Now it's fixed!

Version 2.2.0-beta01

---

README.md
gradle.properties
gradle/gradle-bintray-push.gradle

Version 2.2.0

---

ble/src/main/java/no/nordicsemi/android/ble/AwaitingRequest.java
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/ConditionalWaitRequest.java
ble/src/main/java/no/nordicsemi/android/ble/Request.java

This PR adds API to ensure link encryption. On all current Android versions this means removing the old and creating new bond.

Ensuring bond

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
build.gradle
gradle.properties

Bugs fixed:
- Null Pointers fixed (#216).
- Closing manager when disconnect request was executed, but the manager was disconnected.
- Other minor improvements.

Version 2.2.4

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

Fix for https://github.com/NordicSemiconductor/Android-BLE-Library/issues/276

Remove outdated documentation on getGattCallback()

---

ble-livedata/src/main/java/no/nordicsemi/android/ble/livedata/ObservableBleManager.java

Making ObservableBleManager public

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Disabling indications fixed

---

ble/src/main/java/no/nordicsemi/android/ble/data/Data.java
ble/src/main/java/no/nordicsemi/android/ble/data/MutableData.java
ble/src/test/java/no/nordicsemi/android/ble/data/DataTest.java

Big Endian format types added

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/state/ConnectionState.kt

State mapping fixed

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Null checks for service discovery

---

moustache/README.mo

Readme fixed

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #414.
As `onPhyUpdate(..)` callback doesn't get called on Android 13 (see mentioned issue), as a workaround we initiate a *read PHY* operation (giving 1 sec to change its mind). `onPhyRead(..)` callback seems to be working and it is completing the request initiated with `setPreferredPhy(...)`.

Reading PHY if no callback for setting preferred one

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR makes sure that no request is added to `initQueue` from outside `initialize()` method.

Blocking adding requests to init queue from outside of initialize()

---

ble-common/build.gradle
ble-ktx/build.gradle
ble-livedata/build.gradle
ble/build.gradle
build.gradle
examples/ble-gatt-client/build.gradle
examples/ble-gatt-client/src/main/AndroidManifest.xml
examples/ble-gatt-client/src/main/java/no/nordicsemi/android/ble/ble_gatt_client/GattService.kt
examples/ble-gatt-client/src/main/java/no/nordicsemi/android/ble/ble_gatt_client/MainActivity.kt
examples/ble-gatt-server/build.gradle
examples/ble-gatt-server/src/main/AndroidManifest.xml
examples/ble-gatt-server/src/main/java/no/nordicsemi/android/ble/ble_gatt_server/GattService.kt
examples/ble-gatt-server/src/main/java/no/nordicsemi/android/ble/ble_gatt_server/MainActivity.kt
examples/ble-gatt-server/src/main/res/layout/activity_main.xml
examples/trivia/build.gradle
examples/trivia/src/main/java/no/nordicsemi/android/ble/trivia/client/ClientScreen.kt
examples/trivia/src/main/java/no/nordicsemi/android/ble/trivia/server/ServerScreen.kt
gradle/publish-module.gradle
gradle/wrapper/gradle-wrapper.properties
test/build.gradle
test/src/main/java/no/nordicsemi/andorid/ble/test/client/view/ClientScreen.kt
test/src/main/java/no/nordicsemi/andorid/ble/test/server/view/ServerScreen.kt

This PR updates all the dependencies of the library modules and sample apps.
All issues in the sample apps related to the migration have been fixed and they are now working.

Dependencies + related fixes

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Delaying methods without blocking user's thread

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #514 by fixing what #517 broke.

Bug fixed: delaying execution from a thread without a looper

---

ble/src/main/java/no/nordicsemi/android/ble/ReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ValueChangedCallback.java
ble/src/main/java/no/nordicsemi/android/ble/WriteRequest.java

Bug fix: reporting correct values in progress callbacks

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #525. At lease I hope. By reading the code, the changes of an NPE was if `request` was nullified just moment after the non-null check. Oh, Kotlin would have saved us!
This PR adds some "Java NPE checks" hopefully without breaking existing behavior.

Preventing NPE

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Catching SecurityException from setCharacteristicNotification(...)

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes some lint warnigns.

Warnings fixed

---

.github/workflows/deploy-all.yml
.github/workflows/deploy-to-nexus.yml
gradle/publish-module.gradle
gradle/publish-root.gradle

Release config fixed

---

ble/src/main/java/no/nordicsemi/android/ble/Request.java
examples/trivia/src/main/java/no/nordicsemi/android/ble/trivia/client/viewmodel/ClientViewModel.kt

This PR fixed few more lint warnings.

Warnigns fixed

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR also helps #583, as the `request` is assigned to a local property.

Migration `instanceof` to pattern matching from Java 17

---

ble-common/build.gradle
ble-ktx/build.gradle
ble-livedata/build.gradle
ble/build.gradle
build.gradle
examples/ble-gatt-client/build.gradle
examples/ble-gatt-server/build.gradle
examples/trivia/build.gradle
gradle/wrapper/gradle-wrapper.properties

* Compile and Target SDK increased to 36,
* Kotlin 2.2.0
* Deprecation warnings fixed

Dependencies updated
