NordicSemiconductor/Android-BLE-Library

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectionPriorityRequest.java
ble/src/main/java/no/nordicsemi/android/ble/DisconnectRequest.java
ble/src/main/java/no/nordicsemi/android/ble/MainThreadBluetoothGattCallback.java
ble/src/main/java/no/nordicsemi/android/ble/MtuRequest.java
ble/src/main/java/no/nordicsemi/android/ble/PhyRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ReadRssiRequest.java
ble/src/main/java/no/nordicsemi/android/ble/Request.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForValueChangedRequest.java

This PR fixes issues #16, #29, #30. Also adds some tweaks here and there.
It adds some a-bit-breaking changes: shoudlAutoConnect() methods is now a part of ConnectRequest. The old one has been deprecated, will work like before, but may be removed in some future clean-up version.
Also, the library will now automatically retry connection attempts in case of a connection error, like 133, but not when the device is unreachable (error 133 after 30 seconds). To enable it, call `connect(device).retry(count, delay).enqueue()`.

Bugs fixes and other features

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

This PR fixes the #43 issue, when the `BleManager` got stacked in a state where it can't connect and disconnect (or perform any other operations).
The root cause of this issue is receiving a notification after disconnection, when Android decides that the connection is after all active and calls `onConnectionStateChange` with status STATE_CONNECTED.

Close connection after is has opened on its own

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/ReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ValueChangedCallback.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForValueChangedRequest.java
ble/src/main/java/no/nordicsemi/android/ble/data/DataFilter.java

This PR fixes issue #63. A filter can now be assigned to `WaitForValueChangedRequest` and `ValueChangedCallback`, that will skip packets that will not be used to compose a message.

Notification filters

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/TimeoutableRequest.java

BluetoothGatt.close() wrapped in try-catch blocks

---

ble/build.gradle
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java
gradle.properties

Bugs fixed:
* Closing server was causing NPE when managers were closing.
* Fixed NPE when Request Handler was not initialized. This is a breaking change, as `getGattCallbacks()` is now called in the constructor, which implicates that it may not return explicitly initialized field .

Version 2.2.0-alpha06

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

I found a bug when implementing ServerManager.
The request type of sending notification from server is incorrect.

Fix request type for sending notification

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

I implemented GATT server with `BleServerManager`.
The usage in `README.md` was a bit unkind for me.
After read [GATT server support PR](https://github.com/NordicSemiconductor/Android-BLE-Library/pull/143), I understood how to use `BleServerManager`.
I think it is better to add some usage for GATT server implementation with `BleServerManager`.

Fix server manager usage

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerCallbacks.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/observer/BondingObserver.java
ble/src/main/java/no/nordicsemi/android/ble/observer/ConnectionObserver.java

This PR modifies the callbacks again. `DisconnectCallback` has been changed to `ConnectionObserver` and almost all methods, that previously were in the `BleManagerCallbacks` were restored in this class. 
* `onDeviceNotSupported` was removed, instead `onDeviceDisconnected` with reason `REASON_NOT_SUPPORTED` will called.
* `onServicesDiscovered` was removed.

Connection and bonding observers

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerCallbacks.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/observer/BondingObserver.java
ble/src/main/java/no/nordicsemi/android/ble/observer/ConnectionObserver.java
gradle.properties

This version renames `DisconnectCallback` to `ConnectionObserver` and `BondingCallback` to `BondingObserver`. Some methods from the deprecated `BleManagerCallbacks` were restored in the new `ConnectionObserver`.

Version 2.2.0-alpha09

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java
ble/src/main/java/no/nordicsemi/android/ble/observer/ServerObserver.java

This PR renames `ServerCallback` (which previously was names `BleServerManagerCallbacks` to `ServerObserver` and places it into `observer` package.
The `onDeviceDisconnectedFromServer` callback does not have `reason` parameter, as it's not equal to what the client's corresponding callback would give. For example, when a connected device resets, the `onConnectionStateChange` would give status 8 (timeout), and the same callback in `BluetoothGattServerCallback` would give status 0 (success).

Server improvements

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
gradle.properties

Bug fixing release. The failure about device not supported was not delivered to the `fail` callback.

Version 2.2.0-alpha13

---

README.md
ble/build.gradle
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/LegacyBleManager.java
ble/src/main/java/no/nordicsemi/android/ble/Request.java
ble/src/main/java/no/nordicsemi/android/ble/TimeoutableRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForReadRequest.java
gradle.properties

Improvements:
* A new `LegacyBleManager` class added which should make the transition to 2.2.0 easier. It's still a generic class, like `BleManager` used to be.
* Readme updated.
Bugs fixed:
* `ConnectionPriorityRequest` should now complete at most after 200 ms. There were phones running Android 8+ there didn't seem to have native callback (#186).

Version 2.2.0-beta02

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/RequestHandler.java
ble/src/main/java/no/nordicsemi/android/ble/RequestQueue.java

This PR tries to fix #200. 
**Problem:**
When the manager was awaiting a notification or atomic queue was started, the library was unable to send requests split into multiple chunks. `operationInProgress` wasn't cleared, as `awaitingRequest` was not `nil`, causing following requests to be queued, but not executed. The atomic queue or awaiting requests would timeout eventually.
**Solution:**
The PR resets the `operationInProgress` each time a request is added to the beginning of the queue.

Fixing chunked requests when awaiting request

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR deprecates `createBond()` method and introduces `createBondInsecure()`. Also, a note has been added explaining why using this request is not secure.
Basically:
1. This requests succeeds when the bond information is present only on Android device.
2. The link may be unencrypted despite this request success.
How to replicate:
1. Use a device that allows bonding, but does not have any security on any/some characteristics.
2. Trigger bonding using `createBond()`. Observe devices being bonded and link set as secure.
3. Disconnect.
4. Remove bond information from the peripheral (only).
5. Connect again and call `createBond()` again.
The request will succeed immediately, as bond information is still present on Android. `BluetoothDevice.getBondState()` does not check if the link is …

Marking createBond() as insecure

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/RequestHandler.java
ble/src/main/java/no/nordicsemi/android/ble/RequestQueue.java
ble/src/main/java/no/nordicsemi/android/ble/SimpleRequest.java
ble/src/main/java/no/nordicsemi/android/ble/SimpleValueRequest.java
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

This version introduces the following changes and bug fixes:
* `split()` method fixed when used in write request inside atomic queue or as trigger in `waitForNotification` or `waitForIndication` (#200).
* `readRssi()` takes now at most 1 second and times out if no response is received. This may be an issue with connection longer intervals (#114). 
* `createBond()` is now deprecated and was renamed to `createBondInsecure()` (#208). 
* `before(...)` callback is not called before a request that is executed synchronously, unless the request is put into an atomic queue.
Other improvements:
* Migration to Android Studio 4 and Gradle 6.1.1.

Version 2.2.1

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #210 - an issue with 2.2.1, where init queue fails on phones running older Android versions.
On Android 4.3-4 5 and 8-9 the lib tries to enable indications for Service Changed characteristic as a first task in initialization queue. The request is aborted when the devices are not bonded, as not relevant. But the abort was causing next request to be started immediately. This accumulated problems, where the `initQueue` could be nullified before any next request was enqueued, causing NPE. The proposed fix disables executing init queue until initialization isn't set up.

Executing init queue fixed

---

README.md
gradle.properties

Bugs fixed in 2.2.2:
* Automatic write splitting didn't work when write was a added to an atomic queue or as a trigger of `waitForNotification` (#200) (fixed with #211).

Version 2.2.2

---

README.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
gradle.properties

This PR comes against #214. The issue is on Android side, but some API improvements in the BLE library have been added to make sure users understands the issue and risks involved.

Version 2.2.3

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Like https://github.com/NordicSemiconductor/Android-BLE-Library/issues/226 details, it would be better to enqueue an autoConnect=true connect call if the initial autoConnect=false call fails in cases like the title. This will let this library support connecting to peripherals that happen to not be nearby at app startup with a single connect call.
I tested this by observing the logs of an autoConnect=true request when the peripheral is far away. In that case, this is what happens - https://gist.github.com/usikder/363851c49c574b8cd835463434e5ca23.

Improve the handling of ConnectRequests to bonded devices w/ autoConnect=true

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

I ran into an issue where the MTU was not being requested when the device disconnected and reconnected with the same `BleManager`.
I'm still not totally familiar with the state management in `BleManagerHandler` so bear with me; from what I can tell, once the MTU is requested successfully, subsequent calls to `requestMtu(int)` don't actually perform the MTU exchange with the device if the same mtu value is requested.
This is ultimately due to the "fast path" logic in `nextRequest()` when handling the `REQUEST_MTU` request type. If the request mtu value is equal to the current (even if the device was disconnected and reconnected) then the actual request will not get sent.
```java
case REQUEST_MTU: {
final MtuRequest mr = (MtuRequest) request;
if (mtu != mr.getRequiredMtu()
&& …
```

Reset BleManagerHandler MTU to 23 on disconnect

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Hello @philips77 !
While I was working on faster DFUs I encountered the Android BLE bug where writing to and receiving notifications from the same characteristic asynchronously is totally broken.
In the process of working out a hack fix for the bug for `mcumgr`, I was looking around the internet and the android source and noticed that the issue described in #54 is specific to Android API 26 (8.0.0) which is the exact version I have running on the phone I was testing with. In fact, issue #54 was reported with a samsung s9 which originally shipped with Android 8 installed.
It turns out that the fix for this bug was release in API 27 (8.1.0) which means that we only need to not allow the handler in the call to connectGatt for device running API 26.
The android source bug fix can be found …

Update connectGatt version logic to handle bug specifically in API 26

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR changes the behavior of which status is returned as disconnection reason in case `autoConnect` was set to `true` and the connected peer device initiated disconnection. Before the change `ConnectionObserver.REASON_LINK_LOSS` was returned in any case if the flag was enabled. Now, in case it is the device that caused disconnection, the `ConnectionObserver.REASON_TERMINATE_PEER_USER` will be returned instead.
This PR closes #284.

Returning proper disconnection reason if peer disconnected

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectRequest.java

This PR closes #251.
**Note:** It was possible to do the same before, using `BleManager#cancelQueue()`. The new method in `ConnectRequest` calls this method. Adding this method makes the API more readable.

Adding option to cancel pending connection 

---

ble/src/main/java/no/nordicsemi/android/ble/ConditionalWaitRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectionPriorityRequest.java
ble/src/main/java/no/nordicsemi/android/ble/DisconnectRequest.java
ble/src/main/java/no/nordicsemi/android/ble/MtuRequest.java
ble/src/main/java/no/nordicsemi/android/ble/PhyRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ReadRssiRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ReliableWriteRequest.java
ble/src/main/java/no/nordicsemi/android/ble/Request.java
ble/src/main/java/no/nordicsemi/android/ble/RequestQueue.java
ble/src/main/java/no/nordicsemi/android/ble/SetValueRequest.java
ble/src/main/java/no/nordicsemi/android/ble/SleepRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForValueChangedRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WriteRequest.java
ble/src/main/java/no/nordicsemi/android/ble/callback/AfterCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/BeforeCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/ConnectionPriorityCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/DataReceivedCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/DataSentCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/FailCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/InvalidRequestCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/MtuCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/PhyCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/ReadProgressCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/RssiCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/SuccessCallback.java
ble/src/main/java/no/nordicsemi/android/ble/callback/WriteProgressCallback.java

This PR adds `then(BluetoothDevice)` callback to `Reqeust` class. The callback will be invoked when the request has been processed no matter the result. However, if `BluetoothDevice` was not set, `invalid()` callback will be called instead.

Adding "then" callback to Requests

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes an issue reported here: https://github.com/JuulLabs-OSS/mcumgr-android/issues/93
When a different client had been connected to the device which requested MTU change, just after a new client connects it receives `onMtuChanged` with the value requested by the previous client. This happened even before the new client initiated service discovery, so initialization queue was still `null`. Calling `nextRequest` in such case was effectively setting the device ready.
The new check ensures that `nextRequest` is not called before services were discovered, which should help solve the problem.

Skipping processing requests when MTU changed before services were discovered

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

This PR fixes #317. The `writeType` param is now passed directly to the `writeCharacteristic` methods.
Existing `writeCharacteristic` methods without `writeType` have been deprecated.

Adding write type param to writeCharacteristic methods

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectionPriorityRequest.java
ble/src/main/java/no/nordicsemi/android/ble/annotation/LogPriority.java
ble/src/main/java/no/nordicsemi/android/ble/utils/ILogger.java
build.gradle
examples/ble-gatt-client/build.gradle
examples/ble-gatt-server/build.gradle
gradle/wrapper/gradle-wrapper.properties

This PR fixes #346.
The new method 
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/e55d46bf7459d9fb76c71908b861cb01a493f4c8/ble/src/main/java/no/nordicsemi/android/ble/utils/ILogger.java#L32-L37
in `BleManager` and `BleServerManager` allows to omit creating and logging logs on lower priorities. By default, logs from levels `Log.INFO` and higher will be logged, which is a change in default behavior. Previously all logs were produced, even if later ignored. 
To disable logging, return `Log.ERROR` or `Log.ASSERT` from those methods. To restore previous behavior, return `Log.VERBOSE`.

Option to filter logs by priority

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Trying to discover services despite initial bonding failure

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/BleManagerExt.kt
ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/RequestSuspend.kt
ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/ValueChangedCallbackExt.kt
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/Request.java
ble/src/main/java/no/nordicsemi/android/ble/response/ConnectionPriorityResponse.java
ble/src/main/java/no/nordicsemi/android/ble/response/MtuResult.java
ble/src/main/java/no/nordicsemi/android/ble/response/PhyResult.java
ble/src/main/java/no/nordicsemi/android/ble/response/RssiResult.java
ble/src/main/java/no/nordicsemi/android/ble/response/WriteResponse.java

This PR added few more Kotlin extensions.
Before it was possible to use `.suspend()` and `.asFlow()`methods, but those were returning `Data`.
With the new extensions it is possible to use automagical parsing, e.g.:
```Kotlin
val hrmMeasurements: Flow<HeartRateMeasurementResponse> = 
setNotificationCallback(hrmCharacteristic)
.asValidResponseFlow()
```
or 
```kotlin
scope.launch(exceptionHandler) {
val alertLevel: AlertLevelResponse = readCharacteristic(alertLevelCharacteristic)
.suspendForValidResponse()
// [...]
}
```

More ktx extensions

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/RequestSuspend.kt

The exception was thrown on reading device field which was *null*.
The property hasn't been assigned, because callbacks were invoked
in unforeseen order. To fix the issue assigning device was moved
to `before()` callback and to avoid resuming twice the same coroutine
the `resume()` method has been moved to `done()` callback.

Fix issue with null BluetoothDevice field.

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/BleManagerExt.kt
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java

This PR fixes #364.
Both connection and bond state observers can be called multiple times and the same flow instance is returned.
As suggested in the mentioned issue, if a different observer was set, calling `stateAsFlow()` or `bondingStateAsFlow()` will throw.

Returning the same instance of state observers in ktx

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #363.
When `removeBond()` is executed, there are 2 callbacks called in result: disconnection and changing bond state to `BOND_NONE`. They, however, as shown in #363, can come in any order. Until now, the behaviour was different in any of those cases. 
This PR fixes the issue by ensuring that both the `onConnectionStateChange` callback and bond state broadcast listener are called. They still can be called in any order, but neither of them should block execution of the other. The `then` callback of the *Remove Bond* callback should be called in any case.

Making sure then() callback is called for RemoveBond request

---

ble-common/build.gradle
ble-common/src/main/AndroidManifest.xml
ble-ktx/build.gradle
ble-ktx/src/main/AndroidManifest.xml
ble-livedata/build.gradle
ble-livedata/src/main/AndroidManifest.xml
ble/build.gradle
ble/src/main/AndroidManifest.xml
ble/src/main/java/no/nordicsemi/android/ble/WaitForReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WriteRequest.java
ble/src/main/java/no/nordicsemi/android/ble/data/DataSplitter.java
build.gradle

- Increase gradle version.
- Move package name to gradle files.
- Enable sending empty string using WriteRequest.
On Android 12 (and perhaps before as well), `gatt.writeCharacteristic(...)` returns *false* if the characteristic value is *null*. This effectively disallow sending empty packets. This PR changes *null* to an empty array to workaround it.

Allow sending empty packets

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectionPriorityRequest.java
ble/src/main/java/no/nordicsemi/android/ble/callback/ConnectionParametersUpdatedCallback.java
ble/src/main/java/no/nordicsemi/android/ble/response/ConnectionPriorityResponse.java

This PR introduces a way to set connection parameters listener. This works only for Android 8+.
The `ConnectionPriorityCallback` interface has been deprecated in favor of `ConnectionParametersUpdatedCallback`.
For migration, just change the interface name. Everything else should be the same.

Feature: Connection parameters listener

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/BleManagerExt.kt
ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/RequestSuspend.kt
ble/src/main/java/no/nordicsemi/android/ble/AwaitingRequest.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectRequest.java
ble/src/main/java/no/nordicsemi/android/ble/ReliableWriteRequest.java
ble/src/main/java/no/nordicsemi/android/ble/RequestHandler.java
ble/src/main/java/no/nordicsemi/android/ble/RequestQueue.java
ble/src/main/java/no/nordicsemi/android/ble/SimpleRequest.java
ble/src/main/java/no/nordicsemi/android/ble/SleepRequest.java
ble/src/main/java/no/nordicsemi/android/ble/TimeoutableRequest.java
ble/src/main/java/no/nordicsemi/android/ble/TimeoutableValueRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForValueChangedRequest.java

This PR adds support for cancellation of selected requests.
Bluetooth LE requests, which extend `SimpleRequest` cannot be cancelled. In Android API, each `BluetoothGatt` method triggers corresponding call in `BluetoothGattCallback`.
* New `cancel()` method added to `TimetoutableRequest`.
* `RequestQueue` now extends `TimeoutableRequest` making it and `ReliableWriteRequest` both cancellable and timetable. Mind, that `SimpleRequest`s added to those queues won't be cancelled, but the queue itself can be.
* `SleepRequest` now extends `TimeoutableRequest` and the timeout is used as waking up mechanism (eacbad45f98c5299b5e805f8ab8b186635a25832).
* A request that has completed or was cancelled cannot be enqueued again (each request can be enqueued just once).
* Logging improvement - logs related …

Cancellation support

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java

This PR makes use of the new Bluetooth LE API added in Android 13 (API 33).
It solves #419.
Still, `characteristic.setValue(..)` and `descriptor.setValue(..)` are used in some places for:
1. older Android versions
2. holding a values of shared server characteristics and descriptors
Beside that, the PR removes some warnings here and there.

Migration to API 33

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR makes use of the new `BluetoothGattCallback` methods added in API 33 (Android 13):
* [onCharacteristicChanged](https://developer.android.com/reference/android/bluetooth/BluetoothGattCallback?hl=en#onCharacteristicChanged(android.bluetooth.BluetoothGatt,%20android.bluetooth.BluetoothGattCharacteristic,%20byte[])),
* [onCharacteristicRead](https://developer.android.com/reference/android/bluetooth/BluetoothGattCallback?hl=en#onCharacteristicRead(android.bluetooth.BluetoothGatt,%20android.bluetooth.BluetoothGattCharacteristic,%20byte[],%20int))
Both return `value` as a parameter, instead of part of `characteristic`. This change was made to avoid race conditions, as the `characteristic.value` fields was used both for writing and notifications.

Migration to API 33, part 2

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/WaitForReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/data/DataProvider.java

This PR solves #385.
So far, when setting up a readable server characteristic (or descriptor), there were 2 options to provide a value for a read request sent from a client:
1. Using `setCharacteristicValue(...)` request:
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/2f1fb7b39e420a57e3ce8f8e1eb3e05b7e4170ac/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L1120-L1125 
2. Using `waitForRead(...)` request:
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/2f1fb7b39e420a57e3ce8f8e1eb3e05b7e4170ac/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L1009-L1013
However, as described in the issue mentioned above, sometimes a live value needs to be provided. The server would have to update the characteristic value using 1. periodically even if …

Data provider for read requests

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Reset connection flags when Bluetooth goes off

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/RequestSuspend.kt

This PR fixes an issue introduced in recent alpha versions, where the `suspend()` method in `ble-ktx` has been split into 2: cancelable and non-cancelable.
The latter one has been set as an extension to `SimpleRequest` (all BLE commands), but not to `Request`, leaving creation on bond without `suspend()` support.

Bug fix: `createBondInsecure()` cannot be suspended

---

ble/src/main/java/no/nordicsemi/android/ble/WriteRequest.java

When doing Reliable Write, the client is responsible for verifying the written data. This has sense, actually, only when Write With Response is used. In this case the device confirms the data sent.
This PR removes the check when write type is not `BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT`.

Don't verify write without response operations

---

README.md
USAGE.md
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
moustache/README.mo

This PR simplifies the implementation of a `BleManager`.
The `initialize()`, `isRequiredServiceSupported` and `onServicesInvalidated` methods should now be implemented in the manager class directly, without having to use an inner class.
See https://github.com/NordicSemiconductor/Android-nRF-Blinky/pull/78 for migration guide.

BleManager simplification

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/BleManagerExt.kt

This PR fixes #486.
The reason why `Disconnected` event was not caught using `stateAsFlow` on first connection when using `autoConnect = true` was that in this case the library was immediately starting reconnecting to the target peripheral using `gatt.connect()`. Before that, a new event `Connecting` was sent which was overwriting the state of the manager. As `StateFlow` doesn't have any buffering, a value that was not consumed is overwritten and was lost.
In case of using `autoConnect = false` or in following connections the immediate reconnection didn't happen and disconnection was reported successfully.
This PR breaks a the API. The type returned by `stateAsFlow` and `bondingStateAsFlow` is now `Flow`, not `StateFlow`. If you need a `StateFlow`, use `.stateIn(...)` modifier as such: …

Switching `stateAsFlow` and `bongingStateAsFlow` from StateFlow to SharedFlow

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/callback/FailCallback.java

This PR fixes #474.
Before the change, if notifications or indications were not enabled by client and the server tried to send one, the request was quietly ignored. This might have caused issues when using `suspend()`, as such suspension would never finish.
After the change such request will return in a failure with status `FailCallback.REASON_NOT_ENABLED`. `suspend()` or `await()` methods should throw `RequestFailedException` with that status.

Sending a notification when not enabled returns a failure

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #507.
Reading or writing characteristics or descriptors with some restricted UUIDs may throw `SecurityExeception`. 
This PR adds a try-catch block. The error returned to the user is `FailCallback.REASON_NULL_ATTRIBUTE`.

Catching read and write errors

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Before, service discovery was started from user-provided `Handler` (which defaulted to the UI thread).
It should work with any thread, no need to post the call.

Discovering services from current thread instead of the main thread

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java

This PR fixes #506. At least I hope so. @nadrolinux, please check.
When a server disconnection event is received and corresponding `BleManager` exists, the server manager will call `notifyDeviceDisconnected(...)`, which should reset the states to `STATE_DISCONNECTED` and notify the requests.
Also, when the server manager was set for a `BleManager`, and the device is used as client (that is `connect(..)` is used, the manager now calls `connect(..)` method in the `BluetoothGattServer`. This should make the connection reference persistent in the server. I don't think this is necessary, as it was working before, but should work with it as well.

Server connection events

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #504.
Disconnection result `RESULT_SUCCESS` should now only be returned when the user has requested disconnection using `disconnect()` method. When the connected device goes out or range or is turned off the `REASON_TIMEOUT` should always be returned.

Disconnection reason and events fixed

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java

This PR fixes #526.
I think this is minimal required change to fix the issue. The call to `notifyDeviceDisconnected(...)` was added to `BleServerManager` in #521. It was supposed to fix no disconnection callback in server-only mode when `attachClientConnection` is used.
However, as @corentin-c noticed, that broke bidirectional connection, as that method is now called twice, from server and client, and client doesn't reconnect.
The proposed check ensures that it is called only in server-only mode when `bluetoothGatt` object is null.

Reconnection fixed

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #524.
When the first connection attempt fails, and the library will start to retry connection, this code is invoked:
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/53e169ec7dec77923c50619967b895e8a91091aa/ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java#L639-L648
If the `ConnectRequest` times out, or gets cancelled when the thread is waiting 200 ms, the connection was cancelled, but `connectionState` was never set back to `STATE_DISCONNECTED`.
This PR fixes that by checking the value of `bluetoothGatt` reference after `internalConnect` is called.
In case of *null*, that is when `connectRequest.finished` was *true*, the state is reset to disconnected.
Also, this PR adds another change. When the connection attempt fails, the …

Fixed restoring connection state after cancelled connection attempt

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Hi,
I have been testing Android 14 with bidirectionnal client and server connection, using BleManager.connect with `autoConnect = true` to connect to a Ble device, it works great with all versions below, but seems to be broken on Android 14. I can connect with it, the first disconnection and reconnection works, but after the second disconnection, the device never reconnects.
From what I understand, if autoconnect is used with true, the library first connects with autoConnect false. Then the library uses `gatt.connect()` on the first disconnection to trigger the autoconnect to true. The problem seems that the `gatt.connect()` on Android 14 does not do the same as before, it doesn't set autoConnect to true and works only for the next connection. So after the second disconnection, the device …

Fix autoConnect true not working with Android 14 after the second disconnection

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java

Make the bluetoothDevice value immutable before the null check to fix this request https://github.com/NordicSemiconductor/Android-BLE-Library/issues/539

Make the bluetoothDevice value immutable before the null check

---

ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR closes #541.
Even if the MTU is negotiated to be 517, the library will limit maximum packet length to 512 bytes.

Max usable MTU set to 515 (512 bytes of data)

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

- https://github.com/NordicSemiconductor/Android-BLE-Library/issues/507
- https://issuetracker.google.com/issues/330663537, https://issuetracker.google.com/issues/330663537
- this is a continuation of 229ad11f75f0a85c005a885386aab2cbc5516ff7 where we get read write errors on some Android devices (above api level 33).

Catch security exception on writing / reading characteristics

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

this is fix for https://github.com/NordicSemiconductor/Android-BLE-Library/issues/497
reset connected if autoconnect = true. former code will notify success to connect request even if DISCONNECTED

fix: reset connected if DISCONNECTED is received between connect and initialize for autoconnected

---

ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java

Stumbled across a situation where I want my server to block access to a client device but cannot find a way to disconnect it without first accepting it to build the managed connection. If there is a way I missed, please let me know. I can reflect into the library to get to `cancelConnection` for now but would be nice if there was legit access to it.
This is the basic scenario.
```kotlin
override fun onDeviceConnectedToServer(device: BluetoothDevice) {
val address = device.address
if (allowed(address)) {
val newConnection = ...
newConnection.useServer(this)
newConnection.attachClientConnection(device)        
} else {
Log.d(TAG, "BLE connection blocked $address")
cancelConnection(device)
}
}
```

Provide access to cancelConnection so that a server can deny a client

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/ConnectRequest.java

This is an addition to the auto connect mechanism that offers a different approach while keeping the current API as-is.
The current approach for auto connect is such that the first connection attempt is made using a direct connect (`connectGatt()` with `autoConnect` set to `false`).
This opinionated approach does not fit some use cases well. The main problem being that if the device is not nearby / connectable when the `ConnectRequest` with `useAutoConnect(true)` is enqueued, this will occupy the BLE stack for 30 seconds until timeout (consuming more battery unnecessarily). Scanning for the device first would help with this, but that defeats the purpose of using auto connect (essentially letting the system do the scanning more efficiently).
A secondary problem being that the first connect …

Start auto connect immediately

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/RequestSuspend.kt

The `suspend()` extension functions on various Request types will ignore the cancellation instead of throwing an exception when cancelled via a mechanism other then cancelling the coroutine.
In such cases the code that calls `suspend()` will remain suspended indefinitely.
An example of this is:
Call connect from one coroutine (from within a `BleManager`):
```
connect(bluetoothDevice)
.suspend()
```
While the connect is in progress (within 30 seconds) and before it could succeed, call from another place in the code:
```
cancelQueue()
```
While the connection gets cancelled, the first call will remain suspended.
This PR is an attempt to fix the problem.

Bug fix: suspend extension function remains suspended if the request is cancelled

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

If using `useAutoConnect(true)`:
```
manager.connect(bluetoothDevice)
.useAutoConnect(true)
.suspend()
```
the initial connection will be a normal one (calling `connectGatt()` with `autoConnect = false`). If this fails (times out), the next connect is supposed to use auto connect (with `bluetoothGatt.connect()` or calling `connectGatt()` with `autoConnect = true`).
However, this does not work with a non-bonded device. As mentioned in the Javadoc of `useAutoConnect(true)`, auto connect is still viable to use without a bond when the BLE device has a private static address.
This PR fixes the issue by removing the check for bond in the disconnected state handling.
I believe this is also the cause of this reported issue - https://github.com/NordicSemiconductor/Android-BLE-Library/issues/435

Bug fix: Auto connect not restarting if the initial connection fails when using with a non-bonded device

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

this PR is about to fix #363 case 1, `this.request` will reset to `null` in call of `nextRequest(false)` below and callback for `removeBond` won't be invoked correctly even though bond status change signal is received later. how ever it may introduce unintended side effects as noted in the comment above. Please help to review it.
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/bfcfdf9f5916ac2b06c9de6ed335b11dc53301c2/ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java#L2200-L2212

fix: remove_bond request should be handled after disconnect

---

ble-ktx/build.gradle
ble-livedata/build.gradle
ble/build.gradle
build.gradle
examples/ble-gatt-client/build.gradle
examples/ble-gatt-server/build.gradle
examples/trivia/build.gradle
examples/trivia/src/main/java/no/nordicsemi/android/ble/trivia/client/ClientScreen.kt
examples/trivia/src/main/java/no/nordicsemi/android/ble/trivia/server/ServerScreen.kt
examples/trivia/src/main/java/no/nordicsemi/android/ble/trivia/view/StartScreen.kt
gradle/wrapper/gradle-wrapper.properties
test/build.gradle
test/src/main/java/no/nordicsemi/andorid/ble/test/HomeScreen.kt
test/src/main/java/no/nordicsemi/andorid/ble/test/client/view/ClientScreen.kt
test/src/main/java/no/nordicsemi/andorid/ble/test/server/view/ServerScreen.kt

This PR updates the project dependencies:
- Kotlin migrated 1.9.10 -> 2.0.20 (for sample apps and `ble-ext` module)
- Gradle tools to 8.1.2 -> 8.5.2
- Gradle Wrapper 8.3 -> 8.7
Sample apps were migrated to latest Material and Nordic Common library.

Dependencies updated

---

ble/build.gradle
ble/src/main/java/no/nordicsemi/android/ble/BleManager.java
ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
examples/ble-gatt-server/src/main/java/no/nordicsemi/android/ble/ble_gatt_server/GattService.kt

Although the system broadcasts are exported automatically, it's better to set the `RECEIVER_EXPORTED` flag explicitly.

Registering broadcast receivers as exported

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #548. I don't know how it happened, but the fix should help.

#548 fixed by adding synchronized blocks

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java
ble/src/main/java/no/nordicsemi/android/ble/RequestQueue.java

This PR fixes #552.
When the device gets disconnected while there are some tasks enqueued, the cancelled tasks will be notified and `.fail(...)` or `.invalid(...)` method will be called.
Also, all the tasks of a task queue (`AtomicQueueRequest` or `ReliableWriteRequest`) will be notified when they are removed from the queue (for example on disconnection, or when value validation fails during reliable write).

Bug fix: Cancel tasks when they are removed from the task queue

---

examples/ble-gatt-server/src/main/AndroidManifest.xml

If I launched `ble-gatt-server` app on Android Phone, failed to launch app.
The cause was a lack of permission in AndroidManifest.xml.
Android phone spec is below.
- Galaxy S20
- Android 11
I add `BLUETOOTH_ADMIN` permission to AndroidManifest.xml.

add permission BLUETOOTH_ADMIN

---

test/src/main/java/no/nordicsemi/andorid/ble/test/spec/HeaderBasedPacketMerger.kt

Code optimization

---

examples/trivia/src/main/java/no/nordicsemi/android/ble/trivia/spec/PacketMerger.kt
test/src/main/java/no/nordicsemi/andorid/ble/test/spec/HeaderBasedPacketMerger.kt

This PR fixes #584 and fixes the packet mergers in _trivia_ and _test_ apps.

Bugfix: Packet mergers in sample apps

---

ble/src/main/java/no/nordicsemi/android/ble/ConnectionPriorityRequest.java

Bugfix: invoking value callback using Handler

---

ble/src/main/java/no/nordicsemi/android/ble/ReadRequest.java
ble/src/main/java/no/nordicsemi/android/ble/WriteRequest.java

This PR makes the `WriteRequest` and `ReadRequest` cancellable. These requests can only be canceled if they consist of multiple BLE operations, that is `split` or `merge` are used. Cancellation will abort sending or waiting for more packets, but it will not stop the one that is already in progress (due to Android API requirements).

Making WriteRequest and ReadRequest timeoutable amd cancellable

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

This PR fixes #552, again.
Write and read requests trigger bonding when sent using an unsecured link to a protected attribute. If bonding fails, e.g. it's cancelled, there are 2 things happening:
1. Read characteristic and Read descriptor requests get status 137 in `onCharacteristicRead` callback. This will be ignored.
2. Write characteristic and Write descriptor requests don't get such callback. They don't get any callback, actually.
In both cases, the bond state broadcast receiver gets transition `BOND-BONDING` -> `BOND_NONE`. This PR adds a code to fail awaiting request of write/read type.
If no GATT operation is performed withing 3 seconds after bonding fails, the device gets disconnected (Android disconnects, not the library). However, if there is any GATT operation enqueued and will …

Fixed handling cancelled bonding for read/write operations

---

ble-ktx/src/main/java/no/nordicsemi/android/ble/ktx/ValueChangedCallbackExt.kt

This PR fixes #605. It improves how the data recieved in Notifications are sent to the `Flow` by using `trySendBlocking` instead of `trySend`, which makes only one attempt to send the data. If the consumer is busy, the received data were dropped.

Sending notifications as Flow more reliably

---

ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java

Fix the following Firebase crash:
```
Fatal Exception: java.lang.SecurityException: Need BLUETOOTH_PRIVILEGED permission: Neither user 10049 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
at android.os.Parcel.createExceptionOrNull(Parcel.java:2439)
at android.os.Parcel.createException(Parcel.java:2423)
at android.os.Parcel.readException(Parcel.java:2406)
at android.os.Parcel.readException(Parcel.java:2348)
at android.bluetooth.IBluetoothGatt$Stub$Proxy.clientDisconnect(IBluetoothGatt.java:2526)
at android.bluetooth.BluetoothGatt.disconnect(BluetoothGatt.java:1005)
at no.nordicsemi.android.ble.BleManagerHandler.internalDisconnect(BleManagerHandler.java:813)
at no.nordicsemi.android.ble.BleManagerHandler.onRequestTimeout(BleManagerHandler.java:1717)
at …
```

Fix the issue where gatt.disconnect() may throw a SecurityException
